"""Native-Agent runtime and deterministic control-plane integration points."""

from .contracts import (
    ArtifactRef,
    ContextSnapshot,
    EvidenceAdmission,
    GraphIdentity,
    HandoffReceipt,
    RunRequest,
    RunResult,
    SourceIdentity,
    TaskSnapshot,
    admit_evidence,
    validate_handoff_receipt,
)
from .runtime import (
    AgentsSdkRuntime,
    RecordingTraceProcessor,
    SDK_PACKAGE,
    SDK_VERSION,
    SdkUnavailableError,
    UnsupportedToolError,
)
from .learning import (
    DEFECT_ID,
    HISTORICAL_REGRESSION_CASES,
    LearningClosureError,
    LearningClosureResult,
    PROMOTION_DECISION,
    RegressionReplay,
    execute_learning_closure,
    replay_historical_release_attacks,
    verify_learning_closure,
)
from .vertical_slice import (
    ReleaseTopologyError,
    SliceArtifact,
    VerticalSliceError,
    VerticalSliceResult,
    VerticalSliceRunner,
    derive_release,
)
from .public_proof import (
    PROOF_FILES,
    PROOF_SCHEMA,
    PublicProofError,
    generate_public_proof,
    verify_public_proof,
)
from .hosted_canary import (
    HostedCanaryPolicy,
    HostedCanaryPreflightError,
    HostedCanaryPreflightReceipt,
    HostedCanaryRequest,
    preflight_hosted_canary,
)

__all__ = [
    "AgentsSdkRuntime",
    "ArtifactRef",
    "ContextSnapshot",
    "EvidenceAdmission",
    "GraphIdentity",
    "HISTORICAL_REGRESSION_CASES",
    "HandoffReceipt",
    "HostedCanaryPolicy",
    "HostedCanaryPreflightError",
    "HostedCanaryPreflightReceipt",
    "HostedCanaryRequest",
    "RecordingTraceProcessor",
    "RegressionReplay",
    "RunRequest",
    "RunResult",
    "SDK_PACKAGE",
    "SDK_VERSION",
    "SdkUnavailableError",
    "SourceIdentity",
    "TaskSnapshot",
    "UnsupportedToolError",
    "DEFECT_ID",
    "LearningClosureError",
    "LearningClosureResult",
    "PROMOTION_DECISION",
    "PROOF_FILES",
    "PROOF_SCHEMA",
    "PublicProofError",
    "ReleaseTopologyError",
    "SliceArtifact",
    "VerticalSliceError",
    "VerticalSliceResult",
    "VerticalSliceRunner",
    "admit_evidence",
    "derive_release",
    "execute_learning_closure",
    "generate_public_proof",
    "preflight_hosted_canary",
    "replay_historical_release_attacks",
    "validate_handoff_receipt",
    "verify_learning_closure",
    "verify_public_proof",
]
